apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
        workerType: "fargate" # TODO: Conditional based on .value
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - image: ghcr.io/web3-storage/aws-ipfs-bitswap-peer/app:{{ .Values.image.version }}
        name: {{ .Release.Name }}-{{ .Chart.Name }}        
        env: 
        - name: PORT
          value: {{ .Values.service.port | squote }} 
        - name: NODE_ENV
          value: {{ .Values.env.nodeEnv }}        
        - name: PEER_ID_S3_BUCKET
          value: {{ .Values.env.peerIdS3Bucket }}
        - name: PEER_ID_FILE
          value: {{ .Values.env.peerIdFileName }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu}}
            memory: {{ .Values.resources.limits.memory}}
          requests:
            cpu: {{ .Values.resources.requests.cpu}}
            memory: {{ .Values.resources.requests.memory}}
