---
name: Build And Deploy Dev
on:
  push:
    branches: [dev, env-workflows] # TODO: Just DEV
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs:
  build:
    permissions:
      packages: write
    uses: ipfs-elastic-provider/ipfs-elastic-provider-bitswap-peer/.github/workflows/shared-build.yaml@env-workflows # TODO: @dev
    with:
      docker_image_version_label: dev
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    steps:
    - name: Checkout deployment repository
      uses: actions/checkout@v3
      with:
        repository: ipfs-elastic-provider/ipfs-elastic-provider-bitswap-peer-deployment
        path: deployment
        token: ${{ secrets.DEPLOYMENT_PERSONAL_ACCESS_TOKEN }}
    - name: Deploy new image
      run: |
        cd deployment
        git config user.name ${{ github.actor }}
        git config user.email ${{ github.actor }}@users.noreply.github.com
        yq -iP ".image.version=\"${{ env.BUILD_DATE }}-dev\"" helm/values-dev.yaml
        git commit -am "feat: Deployed version ${{ env.PACKAGE_VERSION }}-dev-${{ env.BUILD_DATE }}-dev."
        git push
