---
name: Staging/Prod | Build And Deploy
on:
  push:
    branches: [main]
env:
  REGISTRY: ghcr.io
jobs:
  build:
    permissions:
      packages: write
    uses: elastic-ipfs/bitswap-peer/.github/workflows/shared-build.yaml@main
