---
name: Dev | Build 
on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs:
  build:
    permissions:
      packages: write
    uses: elastic-ipfs/bitswap-peer/.github/workflows/shared-build.yaml@main
    with:
      docker_image_version_suffix_label: dev
