---
name: Build And Deploy Dev
on:
  push:
    branches: [dev] 
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs:
  build:
    permissions:
      packages: write
    uses: elastic-ipfs/bitswap-peer/.github/workflows/shared-build.yaml@dev
    with:
      docker_image_version_suffix_label: dev
  deploy:
    uses: elastic-ipfs/bitswap-peer/.github/workflows/shared-deploy.yaml@dev
    needs: build
    with:
      deploy_to_environment: dev
      docker_image_version: ${{ needs.build.outputs.build_date }}-dev
    secrets:
      deployment_personal_access_token: ${{ secrets.DEPLOYMENT_PERSONAL_ACCESS_TOKEN }}
