---
name: Dev | Build 
on:
  # ************* Remove after validated
  push:
    branches: [rollback-deploy-dev-workflow]
   # *************
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs:
  build:
    permissions:
      packages: write
    uses: elastic-ipfs/bitswap-peer/.github/workflows/shared-build.yaml@rollback-deploy-dev-workflow # Rename to main
    with:
      docker_image_version_suffix_label: dev
  deploy:
    uses: elastic-ipfs/bitswap-peer/.github/workflows/shared-deploy.yaml@rollback-deploy-dev-workflow # Rename to main
    needs: build
    with:
      deploy_to_environment: dev
      docker_image_version: ${{ needs.build.outputs.build_date }}-dev
    secrets:
      deployment_personal_access_token: ${{ secrets.GH_TOKEN }}

