---
name: Staging/Prod | Build
on:
  push:
    branches: [upgrade-cache-action] # TODO: main
env:
  REGISTRY: ghcr.io
jobs:
  build:
    permissions:
      packages: write
    uses: elastic-ipfs/bitswap-peer/.github/workflows/shared-build.yaml@upgrade-cache-action # TODO: main
    with: # TODO: Remove
      docker_image_version_suffix_label: upgrade-workflow-test
