---
name: Build And Deploy Dev
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs:
  build:
    permissions:
      packages: write
    uses: elastic-ipfs/bitswap-peer/.github/workflows/shared-build.yaml@main
    with:
      docker_image_version_suffix_label: dev
  deploy:
    uses: elastic-ipfs/bitswap-peer/.github/workflows/shared-deploy.yaml@main
    needs: build
    with:
      deploy_to_environment: dev
      docker_image_version: ${{ needs.build.outputs.build_date }}-dev
    secrets:
      deployment_personal_access_token: ${{ secrets.GH_TOKEN }}
