---
name: Deploy
on:
  push:
    branches: [master]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js Current
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package.json') }}
      - name: Install dependencies
        run: |
          echo PACKAGE_VERSION=$(cat package.json | jq -r '.version') >> $GITHUB_ENV
          npm install
      - name: Lint code
        run: npm run lint
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/app:${{ env.PACKAGE_VERSION }}
            ${{ env.REGISTRY }}/${{ github.repository }}/app:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
