name: PR | Build
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    permissions:
      packages: read
    uses: elastic-ipfs/bitswap-peer/.github/workflows/shared-build.yaml@main
    with:
      docker_image_version_suffix_label: dev

