name: PR | Build
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    permissions:
      packages: read
    uses: elastic-ipfs/bitswap-peer/.github/workflows/shared-build.yaml@upgrade-cache-action # TODO: Rename to main
    with:
      docker_push: false
  echo-ouputs-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: print package_version
        run: echo ${{ needs.build-staging.outputs.package_version }}
      - name: print buid_date
        run: echo ${{ needs.build-staging.outputs.build_date }}
