name: PR Build
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    uses: elastic-ipfs/bitswap-peer/.github/workflows/shared-build.yaml@main
    with:
      docker_push: false
