name: PR Build
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    uses: ipfs-elastic-provider/ipfs-elastic-provider-bitswap-peer/.github/workflows/shared-build.yaml@remove-pr-package-perm
    with:
      docker_push: false
