name: 'Shared CD flow'

on:
  workflow_call:
    inputs:
      deploy_to_environment:
        type: string
        description: Name of GH environment which image be deployed to
        required: false
        default: ''
      docker_image_version:
        type: string
        description: Version label used for building image
        required: false
        default: ''
    secrets: 
      deployment_personal_access_token:
        required: true
        description: Token used to update image version in helm
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_to_environment }}
    steps:
    - name: Checkout deployment repository
      uses: actions/checkout@v3
      with:
        repository: elastic-ipfs/bitswap-peer-deployment
        path: deployment
        token: ${{ secrets.deployment_personal_access_token }}
    - name: Deploy new image with suffix label
      run: |
        cd deployment
        git config user.name ${{ github.actor }}
        git config user.email ${{ github.actor }}@users.noreply.github.com
        yq -iP ".image.version=\"${{ inputs.docker_image_version }}\"" helm/values-${{ inputs.deploy_to_environment }}.yaml
        git commit -am "feat: Deployed version ${{ inputs.docker_image_version }} to environment: ${{ inputs.deploy_to_environment }}."
        git push
  